Webhooks
coralogix/terraform-provider-coralogix pull request #51
Opened 2022-12-21 22:01 UTC by OrNovo

Adding webhook resource and data-source

2022-12-22 05:37 UTC, oded-dd requested changes

2022-12-22 05:37 UTC, oded-dd commented on coralogix/clientset/clientset.go
> +	EnvToRESTUrl = map[string]string{
This is a problem. Let's discuss it.

2023-02-01 16:13 UTC, OrNovo commented on docs/resources/webhook.md
> +  custom {
I changed from _webhook_ to _custom_

2023-02-01 20:15 UTC, oded-dd requested changes

2023-02-01 20:15 UTC, oded-dd commented on examples/webhook/main.tf
> +      "privateKey" : "d3bd1e44-5603-09db-52b6-cce4c850dc9e",
should not have privateKey (security issue)

2023-02-01 20:15 UTC, oded-dd commented on examples/webhook/main.tf
> +    emails = ["or.novog@gmail.com", "or.novogroder@coralgix.com"]
Put email that is not yours

2023-02-01 20:15 UTC, oded-dd commented on examples/webhook/main.tf
> +    url  = "https://coralogix-dev.slack.com/archives/C03NAS1N7FC"
Lets make sure it is not valid channel

2023-02-01 21:06 UTC, OrNovo commented on docs/resources/alert.md
> -      webhook_ids = ["WebhookAlerts"] //change here for existing webhook from your account
This is a breaking change, but I think it required.

2023-02-02 10:40 UTC, oded-dd approved these changes
Added small comment

2023-02-02 10:40 UTC, oded-dd commented on examples/webhook/main.tf
> +            "alert_type_id" : "53d222e2-e7b2-4fa6-80d4-9935425d47dd"
I would show an example with `data`

2023-02-02 12:56 UTC, oded-dd approved these changes

2023-02-02 13:01 UTC, merged