Recording-Rules-Group
coralogix/terraform-provider-coralogix pull request #66
Opened 2023-01-17 18:14 UTC by OrNovo

In development

2023-01-17 21:54 UTC, OrNovo commented
Except for the added files, all other changes are refactor

2023-01-18 04:11 UTC, oded-dd requested changes

2023-01-18 04:11 UTC, oded-dd commented on coralogix/resource_coralogix_recording_rules_group_test.go
> +  		groups {
Indentation

2023-01-18 04:11 UTC, oded-dd commented on docs/data-sources/hosted_dashboard.md
> +- `uid` (String) The unique identifier of a dashboard with the dashboard-type prefix (e.r. - grafana:vgvvfknr)
Should be e.g. instead of e.r. No?

2023-01-18 10:51 UTC, oded-dd approved these changes

2023-01-18 11:35 UTC, merged